dockerversion: "3.8"
services:
   mysql_db:
    image: mysql
    container_name: literature_mysql_db
    restart: always
    stdin_open: true
    ports:
     - "3306:3306"
    environment:
     - MYSQL_ROOT_PASSWORD=root
     - MYSQL_USER=kel2
     - MYSQL_PASSWORD=Literature1
     - MYSQL_DATABASE=literature
   
    volumes:
     - "/home/app/database:/var/lib/mysql"   
     
   literature_be: 
    image: kazamisei98/literature-be:1.3
    container_name: literature_be
    ports: 
     - 5000:5000
    depends_on: 
     - mysql_db

